// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-demo-user-master/internal/dao/internal"
)

// borrowRecordDao is the data access object for the table borrow_record.
// You can define custom methods on it to extend its functionality as needed.
type borrowRecordDao struct {
	*internal.BorrowRecordDao
}

var (
	// BorrowRecord is a globally accessible object for table borrow_record operations.
	BorrowRecord = borrowRecordDao{internal.NewBorrowRecordDao()}
)

// Add your custom methods and functionality below.
